[
{"result":"https://media.giphy.com/media/VQvqcZvuW3NsbR3Vqc/giphy-downsized-large.gif?cid=ecf05e47a38v2m2bnh1336wxy74k9pkeqhjnveu0tpofaieu&rid=giphy-downsized-large.gif&ct=g"},
{"result":"https://media2.giphy.com/media/l0Exk5li8fLoNseGI/giphy.mp4"},
{"result":"https://media2.giphy.com/media/xUA7aS4o9CX9r5t6pi/giphy.mp4"},
{"result":"https://media0.giphy.com/media/d1E21RSf45AA7yQo/giphy.mp4"},
{"result":"https://media1.giphy.com/media/xUA7b8FHbUMA88EnTi/giphy.mp4"},
{"result":"https://media.giphy.com/media/4NiFhYkswlc23a3jO8/giphy.mp4"},
{"result":"https://media.giphy.com/media/25Q7uscUF5a2p1Yptn/giphy.mp4"},
{"result":"https://media.giphy.com/media/ahCWaG1ltKsr6/giphy.mp4"}
]